security:
    # -----------------------------
    # Gestion des mots de passe : https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    # ---------------------------
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # -----------------------------
    # Les providers (qui "fournissent" les utilisateurs) : https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    # -----------------------------
    providers:
        users_in_memory: { memory: null }

        ldap_provider:
            entity:
                class: App\Entity\User
                property: codeAd
    # -----------------------------
    # Les firewalls (zones sécurisées)
    # -----------------------------
    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            lazy: true   # service chargé uniquement si nécessaire
            provider: ldap_provider    # Définit quel fournisseur d’utilisateurs utiliser
            
            custom_authenticators:
                - App\Security\LdapAuthenticator

            # === Déconnexion ===
            logout:
                path: logout              # URL pour se déconnecter
                target: login

            # Activate different ways to authenticate:
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note: Only the *first* matching rule is applied

    # -----------------------------
    # Les rôles et contrôle d'accès
    # -----------------------------
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
